// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/agentprotocol/v1/transport.proto

package agentprotocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionHello struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	HostIdentity              string                 `protobuf:"bytes,1,opt,name=host_identity,json=hostIdentity,proto3" json:"host_identity,omitempty"`
	SessionGeneration         uint64                 `protobuf:"varint,2,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	ProtocolVersion           string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities              []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SessionAttemptId          string                 `protobuf:"bytes,5,opt,name=session_attempt_id,json=sessionAttemptId,proto3" json:"session_attempt_id,omitempty"`
	ConnectionInstanceId      string                 `protobuf:"bytes,6,opt,name=connection_instance_id,json=connectionInstanceId,proto3" json:"connection_instance_id,omitempty"`
	AgentArtifactDigest       string                 `protobuf:"bytes,7,opt,name=agent_artifact_digest,json=agentArtifactDigest,proto3" json:"agent_artifact_digest,omitempty"`
	CredentialBindingRevision int64                  `protobuf:"varint,8,opt,name=credential_binding_revision,json=credentialBindingRevision,proto3" json:"credential_binding_revision,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SessionHello) Reset() {
	*x = SessionHello{}
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHello) ProtoMessage() {}

func (x *SessionHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHello.ProtoReflect.Descriptor instead.
func (*SessionHello) Descriptor() ([]byte, []int) {
	return file_api_agentprotocol_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *SessionHello) GetHostIdentity() string {
	if x != nil {
		return x.HostIdentity
	}
	return ""
}

func (x *SessionHello) GetSessionGeneration() uint64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

func (x *SessionHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *SessionHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SessionHello) GetSessionAttemptId() string {
	if x != nil {
		return x.SessionAttemptId
	}
	return ""
}

func (x *SessionHello) GetConnectionInstanceId() string {
	if x != nil {
		return x.ConnectionInstanceId
	}
	return ""
}

func (x *SessionHello) GetAgentArtifactDigest() string {
	if x != nil {
		return x.AgentArtifactDigest
	}
	return ""
}

func (x *SessionHello) GetCredentialBindingRevision() int64 {
	if x != nil {
		return x.CredentialBindingRevision
	}
	return 0
}

type SessionAccepted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HostIdentity      string                 `protobuf:"bytes,1,opt,name=host_identity,json=hostIdentity,proto3" json:"host_identity,omitempty"`
	SessionGeneration uint64                 `protobuf:"varint,2,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	SessionAttemptId  string                 `protobuf:"bytes,3,opt,name=session_attempt_id,json=sessionAttemptId,proto3" json:"session_attempt_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionAccepted) Reset() {
	*x = SessionAccepted{}
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAccepted) ProtoMessage() {}

func (x *SessionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAccepted.ProtoReflect.Descriptor instead.
func (*SessionAccepted) Descriptor() ([]byte, []int) {
	return file_api_agentprotocol_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *SessionAccepted) GetHostIdentity() string {
	if x != nil {
		return x.HostIdentity
	}
	return ""
}

func (x *SessionAccepted) GetSessionGeneration() uint64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

func (x *SessionAccepted) GetSessionAttemptId() string {
	if x != nil {
		return x.SessionAttemptId
	}
	return ""
}

type SessionRejected struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	RetryAfterMillis uint64                 `protobuf:"varint,2,opt,name=retry_after_millis,json=retryAfterMillis,proto3" json:"retry_after_millis,omitempty"`
	Retryable        bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionRejected) Reset() {
	*x = SessionRejected{}
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRejected) ProtoMessage() {}

func (x *SessionRejected) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRejected.ProtoReflect.Descriptor instead.
func (*SessionRejected) Descriptor() ([]byte, []int) {
	return file_api_agentprotocol_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRejected) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SessionRejected) GetRetryAfterMillis() uint64 {
	if x != nil {
		return x.RetryAfterMillis
	}
	return 0
}

func (x *SessionRejected) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Envelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HostIdentity       string                 `protobuf:"bytes,1,opt,name=host_identity,json=hostIdentity,proto3" json:"host_identity,omitempty"`
	SessionGeneration  uint64                 `protobuf:"varint,2,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	LogicalStream      string                 `protobuf:"bytes,3,opt,name=logical_stream,json=logicalStream,proto3" json:"logical_stream,omitempty"`
	MessageId          string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SchemaVersion      string                 `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	SequenceScope      string                 `protobuf:"bytes,6,opt,name=sequence_scope,json=sequenceScope,proto3" json:"sequence_scope,omitempty"`
	Sequence           uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ResourceGeneration uint64                 `protobuf:"varint,8,opt,name=resource_generation,json=resourceGeneration,proto3" json:"resource_generation,omitempty"`
	PayloadDigest      string                 `protobuf:"bytes,9,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	CorrelationKey     string                 `protobuf:"bytes,10,opt,name=correlation_key,json=correlationKey,proto3" json:"correlation_key,omitempty"`
	Payload            []byte                 `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_agentprotocol_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetHostIdentity() string {
	if x != nil {
		return x.HostIdentity
	}
	return ""
}

func (x *Envelope) GetSessionGeneration() uint64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

func (x *Envelope) GetLogicalStream() string {
	if x != nil {
		return x.LogicalStream
	}
	return ""
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Envelope) GetSequenceScope() string {
	if x != nil {
		return x.SequenceScope
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetResourceGeneration() uint64 {
	if x != nil {
		return x.ResourceGeneration
	}
	return 0
}

func (x *Envelope) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *Envelope) GetCorrelationKey() string {
	if x != nil {
		return x.CorrelationKey
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MessageReceipt struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	HostIdentity              string                 `protobuf:"bytes,1,opt,name=host_identity,json=hostIdentity,proto3" json:"host_identity,omitempty"`
	AcceptedSessionGeneration uint64                 `protobuf:"varint,2,opt,name=accepted_session_generation,json=acceptedSessionGeneration,proto3" json:"accepted_session_generation,omitempty"`
	LogicalStream             string                 `protobuf:"bytes,3,opt,name=logical_stream,json=logicalStream,proto3" json:"logical_stream,omitempty"`
	MessageId                 string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SequenceScope             string                 `protobuf:"bytes,5,opt,name=sequence_scope,json=sequenceScope,proto3" json:"sequence_scope,omitempty"`
	Sequence                  uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PayloadDigest             string                 `protobuf:"bytes,7,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	Disposition               string                 `protobuf:"bytes,8,opt,name=disposition,proto3" json:"disposition,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MessageReceipt) Reset() {
	*x = MessageReceipt{}
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReceipt) ProtoMessage() {}

func (x *MessageReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReceipt.ProtoReflect.Descriptor instead.
func (*MessageReceipt) Descriptor() ([]byte, []int) {
	return file_api_agentprotocol_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *MessageReceipt) GetHostIdentity() string {
	if x != nil {
		return x.HostIdentity
	}
	return ""
}

func (x *MessageReceipt) GetAcceptedSessionGeneration() uint64 {
	if x != nil {
		return x.AcceptedSessionGeneration
	}
	return 0
}

func (x *MessageReceipt) GetLogicalStream() string {
	if x != nil {
		return x.LogicalStream
	}
	return ""
}

func (x *MessageReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageReceipt) GetSequenceScope() string {
	if x != nil {
		return x.SequenceScope
	}
	return ""
}

func (x *MessageReceipt) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MessageReceipt) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *MessageReceipt) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Hello
	//	*Frame_Envelope
	//	*Frame_Accepted
	//	*Frame_Rejected
	//	*Frame_Receipt
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentprotocol_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_api_agentprotocol_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetHello() *SessionHello {
	if x != nil {
		if x, ok := x.Body.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetEnvelope() *Envelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

func (x *Frame) GetAccepted() *SessionAccepted {
	if x != nil {
		if x, ok := x.Body.(*Frame_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *Frame) GetRejected() *SessionRejected {
	if x != nil {
		if x, ok := x.Body.(*Frame_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *Frame) GetReceipt() *MessageReceipt {
	if x != nil {
		if x, ok := x.Body.(*Frame_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Hello struct {
	Hello *SessionHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Frame_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

type Frame_Accepted struct {
	Accepted *SessionAccepted `protobuf:"bytes,3,opt,name=accepted,proto3,oneof"`
}

type Frame_Rejected struct {
	Rejected *SessionRejected `protobuf:"bytes,4,opt,name=rejected,proto3,oneof"`
}

type Frame_Receipt struct {
	Receipt *MessageReceipt `protobuf:"bytes,5,opt,name=receipt,proto3,oneof"`
}

func (*Frame_Hello) isFrame_Body() {}

func (*Frame_Envelope) isFrame_Body() {}

func (*Frame_Accepted) isFrame_Body() {}

func (*Frame_Rejected) isFrame_Body() {}

func (*Frame_Receipt) isFrame_Body() {}

var File_api_agentprotocol_v1_transport_proto protoreflect.FileDescriptor

const file_api_agentprotocol_v1_transport_proto_rawDesc = "" +
	"\n" +
	"$api/agentprotocol/v1/transport.proto\x12\fkim.agent.v1\"\x89\x03\n" +
	"\fSessionHello\x12#\n" +
	"\rhost_identity\x18\x01 \x01(\tR\fhostIdentity\x12-\n" +
	"\x12session_generation\x18\x02 \x01(\x04R\x11sessionGeneration\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12,\n" +
	"\x12session_attempt_id\x18\x05 \x01(\tR\x10sessionAttemptId\x124\n" +
	"\x16connection_instance_id\x18\x06 \x01(\tR\x14connectionInstanceId\x122\n" +
	"\x15agent_artifact_digest\x18\a \x01(\tR\x13agentArtifactDigest\x12>\n" +
	"\x1bcredential_binding_revision\x18\b \x01(\x03R\x19credentialBindingRevision\"\x93\x01\n" +
	"\x0fSessionAccepted\x12#\n" +
	"\rhost_identity\x18\x01 \x01(\tR\fhostIdentity\x12-\n" +
	"\x12session_generation\x18\x02 \x01(\x04R\x11sessionGeneration\x12,\n" +
	"\x12session_attempt_id\x18\x03 \x01(\tR\x10sessionAttemptId\"q\n" +
	"\x0fSessionRejected\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12,\n" +
	"\x12retry_after_millis\x18\x02 \x01(\x04R\x10retryAfterMillis\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\xa9\x03\n" +
	"\bEnvelope\x12#\n" +
	"\rhost_identity\x18\x01 \x01(\tR\fhostIdentity\x12-\n" +
	"\x12session_generation\x18\x02 \x01(\x04R\x11sessionGeneration\x12%\n" +
	"\x0elogical_stream\x18\x03 \x01(\tR\rlogicalStream\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\tR\rschemaVersion\x12%\n" +
	"\x0esequence_scope\x18\x06 \x01(\tR\rsequenceScope\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x12/\n" +
	"\x13resource_generation\x18\b \x01(\x04R\x12resourceGeneration\x12%\n" +
	"\x0epayload_digest\x18\t \x01(\tR\rpayloadDigest\x12'\n" +
	"\x0fcorrelation_key\x18\n" +
	" \x01(\tR\x0ecorrelationKey\x12\x18\n" +
	"\apayload\x18\v \x01(\fR\apayload\"\xc7\x02\n" +
	"\x0eMessageReceipt\x12#\n" +
	"\rhost_identity\x18\x01 \x01(\tR\fhostIdentity\x12>\n" +
	"\x1baccepted_session_generation\x18\x02 \x01(\x04R\x19acceptedSessionGeneration\x12%\n" +
	"\x0elogical_stream\x18\x03 \x01(\tR\rlogicalStream\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12%\n" +
	"\x0esequence_scope\x18\x05 \x01(\tR\rsequenceScope\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12%\n" +
	"\x0epayload_digest\x18\a \x01(\tR\rpayloadDigest\x12 \n" +
	"\vdisposition\x18\b \x01(\tR\vdisposition\"\xad\x02\n" +
	"\x05Frame\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.kim.agent.v1.SessionHelloH\x00R\x05hello\x124\n" +
	"\benvelope\x18\x02 \x01(\v2\x16.kim.agent.v1.EnvelopeH\x00R\benvelope\x12;\n" +
	"\baccepted\x18\x03 \x01(\v2\x1d.kim.agent.v1.SessionAcceptedH\x00R\baccepted\x12;\n" +
	"\brejected\x18\x04 \x01(\v2\x1d.kim.agent.v1.SessionRejectedH\x00R\brejected\x128\n" +
	"\areceipt\x18\x05 \x01(\v2\x1c.kim.agent.v1.MessageReceiptH\x00R\areceiptB\x06\n" +
	"\x04body2I\n" +
	"\x0eAgentTransport\x127\n" +
	"\aConnect\x12\x13.kim.agent.v1.Frame\x1a\x13.kim.agent.v1.Frame(\x010\x01BgZegithub.com/kvm-infrastructure-manager/kvm-infrastructure-manager/api/agentprotocol/v1;agentprotocolv1b\x06proto3"

var (
	file_api_agentprotocol_v1_transport_proto_rawDescOnce sync.Once
	file_api_agentprotocol_v1_transport_proto_rawDescData []byte
)

func file_api_agentprotocol_v1_transport_proto_rawDescGZIP() []byte {
	file_api_agentprotocol_v1_transport_proto_rawDescOnce.Do(func() {
		file_api_agentprotocol_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agentprotocol_v1_transport_proto_rawDesc), len(file_api_agentprotocol_v1_transport_proto_rawDesc)))
	})
	return file_api_agentprotocol_v1_transport_proto_rawDescData
}

var file_api_agentprotocol_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_agentprotocol_v1_transport_proto_goTypes = []any{
	(*SessionHello)(nil),    // 0: kim.agent.v1.SessionHello
	(*SessionAccepted)(nil), // 1: kim.agent.v1.SessionAccepted
	(*SessionRejected)(nil), // 2: kim.agent.v1.SessionRejected
	(*Envelope)(nil),        // 3: kim.agent.v1.Envelope
	(*MessageReceipt)(nil),  // 4: kim.agent.v1.MessageReceipt
	(*Frame)(nil),           // 5: kim.agent.v1.Frame
}
var file_api_agentprotocol_v1_transport_proto_depIdxs = []int32{
	0, // 0: kim.agent.v1.Frame.hello:type_name -> kim.agent.v1.SessionHello
	3, // 1: kim.agent.v1.Frame.envelope:type_name -> kim.agent.v1.Envelope
	1, // 2: kim.agent.v1.Frame.accepted:type_name -> kim.agent.v1.SessionAccepted
	2, // 3: kim.agent.v1.Frame.rejected:type_name -> kim.agent.v1.SessionRejected
	4, // 4: kim.agent.v1.Frame.receipt:type_name -> kim.agent.v1.MessageReceipt
	5, // 5: kim.agent.v1.AgentTransport.Connect:input_type -> kim.agent.v1.Frame
	5, // 6: kim.agent.v1.AgentTransport.Connect:output_type -> kim.agent.v1.Frame
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_agentprotocol_v1_transport_proto_init() }
func file_api_agentprotocol_v1_transport_proto_init() {
	if File_api_agentprotocol_v1_transport_proto != nil {
		return
	}
	file_api_agentprotocol_v1_transport_proto_msgTypes[5].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_Envelope)(nil),
		(*Frame_Accepted)(nil),
		(*Frame_Rejected)(nil),
		(*Frame_Receipt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agentprotocol_v1_transport_proto_rawDesc), len(file_api_agentprotocol_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agentprotocol_v1_transport_proto_goTypes,
		DependencyIndexes: file_api_agentprotocol_v1_transport_proto_depIdxs,
		MessageInfos:      file_api_agentprotocol_v1_transport_proto_msgTypes,
	}.Build()
	File_api_agentprotocol_v1_transport_proto = out.File
	file_api_agentprotocol_v1_transport_proto_goTypes = nil
	file_api_agentprotocol_v1_transport_proto_depIdxs = nil
}
