// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: api/agentprotocol/v1/transport.proto

package agentprotocolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentTransport_Connect_FullMethodName = "/kim.agent.v1.AgentTransport/Connect"
)

// AgentTransportClient is the client API for AgentTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentTransportClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type agentTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentTransportClient(cc grpc.ClientConnInterface) AgentTransportClient {
	return &agentTransportClient{cc}
}

func (c *agentTransportClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentTransport_ServiceDesc.Streams[0], AgentTransport_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTransport_ConnectClient = grpc.BidiStreamingClient[Frame, Frame]

// AgentTransportServer is the server API for AgentTransport service.
// All implementations must embed UnimplementedAgentTransportServer
// for forward compatibility.
type AgentTransportServer interface {
	Connect(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedAgentTransportServer()
}

// UnimplementedAgentTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentTransportServer struct{}

func (UnimplementedAgentTransportServer) Connect(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentTransportServer) mustEmbedUnimplementedAgentTransportServer() {}
func (UnimplementedAgentTransportServer) testEmbeddedByValue()                        {}

// UnsafeAgentTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentTransportServer will
// result in compilation errors.
type UnsafeAgentTransportServer interface {
	mustEmbedUnimplementedAgentTransportServer()
}

func RegisterAgentTransportServer(s grpc.ServiceRegistrar, srv AgentTransportServer) {
	// If the following call panics, it indicates UnimplementedAgentTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentTransport_ServiceDesc, srv)
}

func _AgentTransport_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentTransportServer).Connect(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTransport_ConnectServer = grpc.BidiStreamingServer[Frame, Frame]

// AgentTransport_ServiceDesc is the grpc.ServiceDesc for AgentTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kim.agent.v1.AgentTransport",
	HandlerType: (*AgentTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentTransport_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/agentprotocol/v1/transport.proto",
}
